exports.lines = {
  "bakerloo": "Bakerloo",
  "central": "Central",
  "circle": "Circle",
  "district": "District",
  "hammersmith-city": "Hammersmith & City",
  "jubilee": "Jubilee",
  "metropolitan": "Metropolitan",
  "northern": "Northern",
  "piccadilly": "Piccadilly",
  "victoria": "Victoria",
  "waterloo-city": "Waterloo & City"
};

exports.stations = {
  "940GZZLUBST": "Baker Street Underground Station",
  "940GZZLUCHX": "Charing Cross Underground Station",
  "940GZZLUEAC": "Elephant & Castle Underground Station",
  "940GZZLUEMB": "Embankment Underground Station",
  "940GZZLUERB": "Edgware Road (Bakerloo) Underground Station",
  "940GZZLUHAW": "Harrow & Wealdstone Underground Station",
  "940GZZLUHSN": "Harlesden Underground Station",
  "940GZZLUKEN": "Kenton Underground Station",
  "940GZZLUKPK": "Kilburn Park Underground Station",
  "940GZZLUKSL": "Kensal Green Underground Station",
  "940GZZLULBN": "Lambeth North Underground Station",
  "940GZZLUMVL": "Maida Vale Underground Station",
  "940GZZLUMYB": "Marylebone Underground Station",
  "940GZZLUNWY": "North Wembley Underground Station",
  "940GZZLUOXC": "Oxford Circus Underground Station",
  "940GZZLUPAC": "Paddington Underground Station",
  "940GZZLUPCC": "Piccadilly Circus Underground Station",
  "940GZZLUQPS": "Queen's Park Underground Station",
  "940GZZLURGP": "Regent's Park Underground Station",
  "940GZZLUSGP": "Stonebridge Park Underground Station",
  "940GZZLUSKT": "South Kenton Underground Station",
  "940GZZLUWJN": "Willesden Junction Underground Station",
  "940GZZLUWKA": "Warwick Avenue Underground Station",
  "940GZZLUWLO": "Waterloo Underground Station",
  "940GZZLUWYC": "Wembley Central Underground Station",
  "940GZZLUADE": "Aldgate East Underground Station",
  "940GZZLUBBB": "Bromley-by-Bow Underground Station",
  "940GZZLUBBN": "Barbican Underground Station",
  "940GZZLUBKG": "Barking Underground Station",
  "940GZZLUBWR": "Bow Road Underground Station",
  "940GZZLUEHM": "East Ham Underground Station",
  "940GZZLUERC": "Edgware Road (Circle Line) Underground Station",
  "940GZZLUESQ": "Euston Square Underground Station",
  "940GZZLUFCN": "Farringdon Underground Station",
  "940GZZLUGHK": "Goldhawk Road Underground Station",
  "940GZZLUGPS": "Great Portland Street Underground Station",
  "940GZZLUHSC": "Hammersmith (H&C Line) Underground Station",
  "940GZZLUKSX": "King's Cross St. Pancras Underground Station",
  "940GZZLULAD": "Ladbroke Grove Underground Station",
  "940GZZLULRD": "Latimer Road Underground Station",
  "940GZZLULVT": "Liverpool Street Underground Station",
  "940GZZLUMED": "Mile End Underground Station",
  "940GZZLUMGT": "Moorgate Underground Station",
  "940GZZLUPAH": "Paddington (H&C Line)-Underground",
  "940GZZLUPLW": "Plaistow Underground Station",
  "940GZZLURYO": "Royal Oak Underground Station",
  "940GZZLUSBM": "Shepherd's Bush Market Underground Station",
  "940GZZLUSGN": "Stepney Green Underground Station",
  "940GZZLUUPK": "Upton Park Underground Station",
  "940GZZLUWHM": "West Ham Underground Station",
  "940GZZLUWLA": "Wood Lane Underground Station",
  "940GZZLUWPL": "Whitechapel Underground Station",
  "940GZZLUWSP": "Westbourne Park Underground Station",
  "940GZZLUBMY": "Bermondsey Underground Station",
  "940GZZLUBND": "Bond Street Underground Station",
  "940GZZLUCGT": "Canning Town Underground Station",
  "940GZZLUCPK": "Canons Park Underground Station",
  "940GZZLUCWR": "Canada Water Underground Station",
  "940GZZLUCYF": "Canary Wharf Underground Station",
  "940GZZLUDOH": "Dollis Hill Underground Station",
  "940GZZLUFYR": "Finchley Road Underground Station",
  "940GZZLUGPK": "Green Park Underground Station",
  "940GZZLUKBN": "Kilburn Underground Station",
  "940GZZLUKBY": "Kingsbury Underground Station",
  "940GZZLULNB": "London Bridge Underground Station",
  "940GZZLUNDN": "Neasden Underground Station",
  "940GZZLUNGW": "North Greenwich Underground Station",
  "940GZZLUQBY": "Queensbury Underground Station",
  "940GZZLUSJW": "St. John's Wood Underground Station",
  "940GZZLUSTD": "Stratford Underground Station",
  "940GZZLUSTM": "Stanmore Underground Station",
  "940GZZLUSWC": "Swiss Cottage Underground Station",
  "940GZZLUSWK": "Southwark Underground Station",
  "940GZZLUWHP": "West Hampstead Underground Station",
  "940GZZLUWIG": "Willesden Green Underground Station",
  "940GZZLUWSM": "Westminster Underground Station",
  "940GZZLUWYP": "Wembley Park Underground Station",
  "940GZZLUBKE": "Barkingside Underground Station",
  "940GZZLUBKH": "Buckhurst Hill Underground Station",
  "940GZZLUBLG": "Bethnal Green Underground Station",
  "940GZZLUBNK": "Bank Underground Station",
  "940GZZLUCHL": "Chancery Lane Underground Station",
  "940GZZLUCWL": "Chigwell Underground Station",
  "940GZZLUDBN": "Debden Underground Station",
  "940GZZLUEAN": "East Acton Underground Station",
  "940GZZLUEBY": "Ealing Broadway Underground Station",
  "940GZZLUEPG": "Epping Underground Station",
  "940GZZLUFLP": "Fairlop Underground Station",
  "940GZZLUGFD": "Greenford Underground Station",
  "940GZZLUGGH": "Grange Hill Underground Station",
  "940GZZLUGTH": "Gants Hill Underground Station",
  "940GZZLUHBN": "Holborn Underground Station",
  "940GZZLUHGR": "Hanger Lane Underground Station",
  "940GZZLUHLT": "Hainault Underground Station",
  "940GZZLUHPK": "Holland Park Underground Station",
  "940GZZLULGN": "Loughton Underground Station",
  "940GZZLULGT": "Lancaster Gate Underground Station",
  "940GZZLULYN": "Leyton Underground Station",
  "940GZZLULYS": "Leytonstone Underground Station",
  "940GZZLUMBA": "Marble Arch Underground Station",
  "940GZZLUNAN": "North Acton Underground Station",
  "940GZZLUNBP": "Newbury Park Underground Station",
  "940GZZLUNHG": "Notting Hill Gate Underground Station",
  "940GZZLUNHT": "Northolt Underground Station",
  "940GZZLUPVL": "Perivale Underground Station",
  "940GZZLUQWY": "Queensway Underground Station",
  "940GZZLURBG": "Redbridge Underground Station",
  "940GZZLURSG": "Ruislip Gardens Underground Station",
  "940GZZLURVY": "Roding Valley Underground Station",
  "940GZZLUSBC": "Shepherd's Bush (Central) Underground Station",
  "940GZZLUSNB": "Snaresbrook Underground Station",
  "940GZZLUSPU": "St. Paul's Underground Station",
  "940GZZLUSRP": "South Ruislip Underground Station",
  "940GZZLUSWF": "South Woodford Underground Station",
  "940GZZLUTCR": "Tottenham Court Road Underground Station",
  "940GZZLUTHB": "Theydon Bois Underground Station",
  "940GZZLUWCY": "White City Underground Station",
  "940GZZLUWOF": "Woodford Underground Station",
  "940GZZLUWRP": "West Ruislip Underground Station",
  "940GZZLUWSD": "Wanstead Underground Station",
  "940GZZLUWTA": "West Acton Underground Station",
  "940GZZLUALD": "Aldgate Underground Station",
  "940GZZLUBKF": "Blackfriars Underground Station",
  "940GZZLUBWT": "Bayswater Underground Station",
  "940GZZLUCST": "Cannon Street Underground Station",
  "940GZZLUECT": "Earl's Court Underground Station",
  "940GZZLUGTR": "Gloucester Road Underground Station",
  "940GZZLUHSK": "High Street Kensington Underground Station",
  "940GZZLUMMT": "Monument Underground Station",
  "940GZZLUMSH": "Mansion House Underground Station",
  "940GZZLUSJP": "St. James's Park Underground Station",
  "940GZZLUSKS": "South Kensington Underground Station",
  "940GZZLUSSQ": "Sloane Square Underground Station",
  "940GZZLUTMP": "Temple Underground Station",
  "940GZZLUTWH": "Tower Hill Underground Station",
  "940GZZLUVIC": "Victoria Underground Station",
  "910GBLFR": "London Blackfriars Rail Station",
  "940GZZLUACT": "Acton Town Underground Station",
  "940GZZLUBEC": "Becontree Underground Station",
  "940GZZLUBSC": "Barons Court Underground Station",
  "940GZZLUCWP": "Chiswick Park Underground Station",
  "940GZZLUDGE": "Dagenham East Underground Station",
  "940GZZLUDGY": "Dagenham Heathway Underground Station",
  "940GZZLUECM": "Ealing Common Underground Station",
  "940GZZLUEPK": "Elm Park Underground Station",
  "940GZZLUEPY": "East Putney Underground Station",
  "940GZZLUFBY": "Fulham Broadway Underground Station",
  "940GZZLUGBY": "Gunnersbury Underground Station",
  "940GZZLUHCH": "Hornchurch Underground Station",
  "940GZZLUHSD": "Hammersmith (Dist&Picc Line) Underground Station",
  "940GZZLUKOY": "Kensington (Olympia) Underground Station",
  "940GZZLUKWG": "Kew Gardens Underground Station",
  "940GZZLUPSG": "Parsons Green Underground Station",
  "940GZZLUPYB": "Putney Bridge Underground Station",
  "940GZZLURMD": "Richmond Underground Station",
  "940GZZLURVP": "Ravenscourt Park Underground Station",
  "940GZZLUSFB": "Stamford Brook Underground Station",
  "940GZZLUSFS": "Southfields Underground Station",
  "940GZZLUTNG": "Turnham Green Underground Station",
  "940GZZLUUPB": "Upminster Bridge Underground Station",
  "940GZZLUUPM": "Upminster Underground Station",
  "940GZZLUUPY": "Upney Underground Station",
  "940GZZLUWBN": "West Brompton Underground Station",
  "940GZZLUWIM": "Wimbledon Underground Station",
  "940GZZLUWIP": "Wimbledon Park Underground Station",
  "940GZZLUWKN": "West Kensington Underground Station",
  "940GZZLUAMS": "Amersham Underground Station",
  "940GZZLUCAL": "Chalfont & Latimer Underground Station",
  "940GZZLUCSM": "Chesham Underground Station",
  "940GZZLUCXY": "Croxley Underground Station",
  "940GZZLUCYD": "Chorleywood Underground Station",
  "940GZZLUEAE": "Eastcote Underground Station",
  "940GZZLUHGD": "Hillingdon Underground Station",
  "940GZZLUHOH": "Harrow-on-the-Hill Underground Station",
  "940GZZLUICK": "Ickenham Underground Station",
  "940GZZLUMPK": "Moor Park Underground Station",
  "940GZZLUNHA": "North Harrow Underground Station",
  "940GZZLUNKP": "Northwick Park Underground Station",
  "940GZZLUNOW": "Northwood Underground Station",
  "940GZZLUNWH": "Northwood Hills Underground Station",
  "940GZZLUPNR": "Pinner Underground Station",
  "940GZZLUPRD": "Preston Road Underground Station",
  "940GZZLURKW": "Rickmansworth Underground Station",
  "940GZZLURSM": "Ruislip Manor Underground Station",
  "940GZZLURSP": "Ruislip Underground Station",
  "940GZZLURYL": "Rayners Lane Underground Station",
  "940GZZLUUXB": "Uxbridge Underground Station",
  "940GZZLUWAF": "Watford Underground Station",
  "940GZZLUWHW": "West Harrow Underground Station",
  "940GZZLUBLR": "Blackhorse Road Underground Station",
  "940GZZLUBXN": "Brixton Underground Station",
  "940GZZLUEUS": "Euston Underground Station",
  "940GZZLUFPK": "Finsbury Park Underground Station",
  "940GZZLUHAI": "Highbury & Islington Underground Station",
  "940GZZLUPCO": "Pimlico Underground Station",
  "940GZZLUSKW": "Stockwell Underground Station",
  "940GZZLUSVS": "Seven Sisters Underground Station",
  "940GZZLUTMH": "Tottenham Hale Underground Station",
  "940GZZLUVXL": "Vauxhall Underground Station",
  "940GZZLUWRR": "Warren Street Underground Station",
  "940GZZLUWWL": "Walthamstow Central Underground Station",
  "940GZZLUACY": "Archway Underground Station",
  "940GZZLUAGL": "Angel Underground Station",
  "940GZZLUBLM": "Balham Underground Station",
  "940GZZLUBOR": "Borough Underground Station",
  "940GZZLUBTK": "Burnt Oak Underground Station",
  "940GZZLUBTX": "Brent Cross Underground Station",
  "940GZZLUBZP": "Belsize Park Underground Station",
  "940GZZLUCFM": "Chalk Farm Underground Station",
  "940GZZLUCND": "Colindale Underground Station",
  "940GZZLUCPC": "Clapham Common Underground Station",
  "940GZZLUCPN": "Clapham North Underground Station",
  "940GZZLUCPS": "Clapham South Underground Station",
  "940GZZLUCSD": "Colliers Wood Underground Station",
  "940GZZLUCTN": "Camden Town Underground Station",
  "940GZZLUEFY": "East Finchley Underground Station",
  "940GZZLUEGW": "Edgware Underground Station",
  "940GZZLUFYC": "Finchley Central Underground Station",
  "940GZZLUGDG": "Goodge Street Underground Station",
  "940GZZLUGGN": "Golders Green Underground Station",
  "940GZZLUHBT": "High Barnet Underground Station",
  "940GZZLUHCL": "Hendon Central Underground Station",
  "940GZZLUHGT": "Highgate Underground Station",
  "940GZZLUHTD": "Hampstead Underground Station",
  "940GZZLUKNG": "Kennington Underground Station",
  "940GZZLUKSH": "Kentish Town Underground Station",
  "940GZZLULSQ": "Leicester Square Underground Station",
  "940GZZLUMDN": "Morden Underground Station",
  "940GZZLUMHL": "Mill Hill East Underground Station",
  "940GZZLUMTC": "Mornington Crescent Underground Station",
  "940GZZLUODS": "Old Street Underground Station",
  "940GZZLUOVL": "Oval Underground Station",
  "940GZZLUSWN": "South Wimbledon Underground Station",
  "940GZZLUTAW": "Totteridge & Whetstone Underground Station",
  "940GZZLUTBC": "Tooting Bec Underground Station",
  "940GZZLUTBY": "Tooting Broadway Underground Station",
  "940GZZLUTFP": "Tufnell Park Underground Station",
  "940GZZLUWFN": "West Finchley Underground Station",
  "940GZZLUWOP": "Woodside Park Underground Station",
  "910GENFCOAK": "Oakwood Station",
  "940GZZLUALP": "Alperton Underground Station",
  "940GZZLUASG": "Arnos Grove Underground Station",
  "940GZZLUASL": "Arsenal Underground Station",
  "940GZZLUBDS": "Bounds Green Underground Station",
  "940GZZLUBOS": "Boston Manor Underground Station",
  "940GZZLUCAR": "Caledonian Road Underground Station",
  "940GZZLUCGN": "Covent Garden Underground Station",
  "940GZZLUCKS": "Cockfosters Underground Station",
  "940GZZLUHNX": "Hatton Cross Underground Station",
  "940GZZLUHPC": "Hyde Park Corner Underground Station",
  "940GZZLUHR4": "Heathrow Terminal 4 Underground Station",
  "940GZZLUHR5": "Heathrow Terminal 5 Underground Station",
  "940GZZLUHRC": "Heathrow Terminals 1-2-3 Underground Station ",
  "940GZZLUHWC": "Hounslow Central Underground Station",
  "940GZZLUHWE": "Hounslow East Underground Station",
  "940GZZLUHWT": "Hounslow West Underground Station",
  "940GZZLUHWY": "Holloway Road Underground Station",
  "940GZZLUKNB": "Knightsbridge Underground Station",
  "940GZZLUMRH": "Manor House Underground Station",
  "940GZZLUNEN": "North Ealing Underground Station",
  "940GZZLUNFD": "Northfields Underground Station",
  "940GZZLUOAK": "Oakwood Underground Station",
  "940GZZLUOSY": "Osterley Underground Station",
  "940GZZLUPKR": "Park Royal Underground Station",
  "940GZZLURSQ": "Russell Square Underground Station",
  "940GZZLUSEA": "South Ealing Underground Station",
  "940GZZLUSGT": "Southgate Underground Station",
  "940GZZLUSHH": "South Harrow Underground Station",
  "940GZZLUSUH": "Sudbury Hill Underground Station",
  "940GZZLUSUT": "Sudbury Town Underground Station",
  "940GZZLUTPN": "Turnpike Lane Underground Station",
  "940GZZLUWOG": "Wood Green Underground Station"
};

exports.stationsOnLines = {
  "bakerloo": [
    "940GZZLUBST",
    "940GZZLUCHX",
    "940GZZLUEAC",
    "940GZZLUEMB",
    "940GZZLUERB",
    "940GZZLUHAW",
    "940GZZLUHSN",
    "940GZZLUKEN",
    "940GZZLUKPK",
    "940GZZLUKSL",
    "940GZZLULBN",
    "940GZZLUMVL",
    "940GZZLUMYB",
    "940GZZLUNWY",
    "940GZZLUOXC",
    "940GZZLUPAC",
    "940GZZLUPCC",
    "940GZZLUQPS",
    "940GZZLURGP",
    "940GZZLUSGP",
    "940GZZLUSKT",
    "940GZZLUWJN",
    "940GZZLUWKA",
    "940GZZLUWLO",
    "940GZZLUWYC"
  ],
  "central": [
    "940GZZLUBKE",
    "940GZZLUBKH",
    "940GZZLUBLG",
    "940GZZLUBND",
    "940GZZLUBNK",
    "940GZZLUCHL",
    "940GZZLUCWL",
    "940GZZLUDBN",
    "940GZZLUEAN",
    "940GZZLUEBY",
    "940GZZLUEPG",
    "940GZZLUFLP",
    "940GZZLUGFD",
    "940GZZLUGGH",
    "940GZZLUGTH",
    "940GZZLUHBN",
    "940GZZLUHGR",
    "940GZZLUHLT",
    "940GZZLUHPK",
    "940GZZLULGN",
    "940GZZLULGT",
    "940GZZLULVT",
    "940GZZLULYN",
    "940GZZLULYS",
    "940GZZLUMBA",
    "940GZZLUMED",
    "940GZZLUNAN",
    "940GZZLUNBP",
    "940GZZLUNHG",
    "940GZZLUNHT",
    "940GZZLUOXC",
    "940GZZLUPVL",
    "940GZZLUQWY",
    "940GZZLURBG",
    "940GZZLURSG",
    "940GZZLURVY",
    "940GZZLUSBC",
    "940GZZLUSNB",
    "940GZZLUSPU",
    "940GZZLUSRP",
    "940GZZLUSTD",
    "940GZZLUSWF",
    "940GZZLUTCR",
    "940GZZLUTHB",
    "940GZZLUWCY",
    "940GZZLUWOF",
    "940GZZLUWRP",
    "940GZZLUWSD",
    "940GZZLUWTA"
  ],
  "circle": [
    "940GZZLUADE",
    "940GZZLUALD",
    "940GZZLUBBB",
    "940GZZLUBBN",
    "940GZZLUBKF",
    "940GZZLUBKG",
    "940GZZLUBST",
    "940GZZLUBWR",
    "940GZZLUBWT",
    "940GZZLUCST",
    "940GZZLUECT",
    "940GZZLUEHM",
    "940GZZLUEMB",
    "940GZZLUERC",
    "940GZZLUESQ",
    "940GZZLUFCN",
    "940GZZLUGHK",
    "940GZZLUGPS",
    "940GZZLUGTR",
    "940GZZLUHSC",
    "940GZZLUHSK",
    "940GZZLUKSX",
    "940GZZLULAD",
    "940GZZLULRD",
    "940GZZLULVT",
    "940GZZLUMED",
    "940GZZLUMGT",
    "940GZZLUMMT",
    "940GZZLUMSH",
    "940GZZLUNHG",
    "940GZZLUPAC",
    "940GZZLUPAH",
    "940GZZLUPLW",
    "940GZZLURYO",
    "940GZZLUSBM",
    "940GZZLUSGN",
    "940GZZLUSJP",
    "940GZZLUSKS",
    "940GZZLUSSQ",
    "940GZZLUTMP",
    "940GZZLUTWH",
    "940GZZLUUPK",
    "940GZZLUVIC",
    "940GZZLUWHM",
    "940GZZLUWLA",
    "940GZZLUWPL",
    "940GZZLUWSM",
    "940GZZLUWSP"
  ],
  "district": [
    "910GBLFR",
    "940GZZLUACT",
    "940GZZLUADE",
    "940GZZLUBBB",
    "940GZZLUBEC",
    "940GZZLUBKF",
    "940GZZLUBKG",
    "940GZZLUBSC",
    "940GZZLUBWR",
    "940GZZLUBWT",
    "940GZZLUCST",
    "940GZZLUCWP",
    "940GZZLUDGE",
    "940GZZLUDGY",
    "940GZZLUEBY",
    "940GZZLUECM",
    "940GZZLUECT",
    "940GZZLUEHM",
    "940GZZLUEMB",
    "940GZZLUEPK",
    "940GZZLUEPY",
    "940GZZLUERC",
    "940GZZLUFBY",
    "940GZZLUGBY",
    "940GZZLUGHK",
    "940GZZLUGTR",
    "940GZZLUHCH",
    "940GZZLUHSC",
    "940GZZLUHSD",
    "940GZZLUHSK",
    "940GZZLUKOY",
    "940GZZLUKWG",
    "940GZZLULAD",
    "940GZZLULRD",
    "940GZZLUMED",
    "940GZZLUMMT",
    "940GZZLUMSH",
    "940GZZLUNHG",
    "940GZZLUPAC",
    "940GZZLUPAH",
    "940GZZLUPLW",
    "940GZZLUPSG",
    "940GZZLUPYB",
    "940GZZLURMD",
    "940GZZLURVP",
    "940GZZLURYO",
    "940GZZLUSBM",
    "940GZZLUSFB",
    "940GZZLUSFS",
    "940GZZLUSGN",
    "940GZZLUSJP",
    "940GZZLUSKS",
    "940GZZLUSSQ",
    "940GZZLUTMP",
    "940GZZLUTNG",
    "940GZZLUTWH",
    "940GZZLUUPB",
    "940GZZLUUPK",
    "940GZZLUUPM",
    "940GZZLUUPY",
    "940GZZLUVIC",
    "940GZZLUWBN",
    "940GZZLUWHM",
    "940GZZLUWIM",
    "940GZZLUWIP",
    "940GZZLUWKN",
    "940GZZLUWLA",
    "940GZZLUWPL",
    "940GZZLUWSM",
    "940GZZLUWSP"
  ],
  "hammersmith-city": [
    "940GZZLUADE",
    "940GZZLUBBB",
    "940GZZLUBBN",
    "940GZZLUBKG",
    "940GZZLUBST",
    "940GZZLUBWR",
    "940GZZLUEHM",
    "940GZZLUERC",
    "940GZZLUESQ",
    "940GZZLUFCN",
    "940GZZLUGHK",
    "940GZZLUGPS",
    "940GZZLUHSC",
    "940GZZLUKSX",
    "940GZZLULAD",
    "940GZZLULRD",
    "940GZZLULVT",
    "940GZZLUMED",
    "940GZZLUMGT",
    "940GZZLUPAH",
    "940GZZLUPLW",
    "940GZZLURYO",
    "940GZZLUSBM",
    "940GZZLUSGN",
    "940GZZLUUPK",
    "940GZZLUWHM",
    "940GZZLUWLA",
    "940GZZLUWPL",
    "940GZZLUWSP"
  ],
  "jubilee": [
    "940GZZLUBMY",
    "940GZZLUBND",
    "940GZZLUBST",
    "940GZZLUCGT",
    "940GZZLUCPK",
    "940GZZLUCWR",
    "940GZZLUCYF",
    "940GZZLUDOH",
    "940GZZLUFYR",
    "940GZZLUGPK",
    "940GZZLUKBN",
    "940GZZLUKBY",
    "940GZZLULNB",
    "940GZZLUNDN",
    "940GZZLUNGW",
    "940GZZLUQBY",
    "940GZZLUSJW",
    "940GZZLUSTD",
    "940GZZLUSTM",
    "940GZZLUSWC",
    "940GZZLUSWK",
    "940GZZLUWHM",
    "940GZZLUWHP",
    "940GZZLUWIG",
    "940GZZLUWLO",
    "940GZZLUWSM",
    "940GZZLUWYP"
  ],
  "metropolitan": [
    "940GZZLUALD",
    "940GZZLUAMS",
    "940GZZLUBBN",
    "940GZZLUBST",
    "940GZZLUCAL",
    "940GZZLUCSM",
    "940GZZLUCXY",
    "940GZZLUCYD",
    "940GZZLUEAE",
    "940GZZLUESQ",
    "940GZZLUFCN",
    "940GZZLUFYR",
    "940GZZLUGPS",
    "940GZZLUHGD",
    "940GZZLUHOH",
    "940GZZLUICK",
    "940GZZLUKSX",
    "940GZZLULVT",
    "940GZZLUMGT",
    "940GZZLUMPK",
    "940GZZLUNHA",
    "940GZZLUNKP",
    "940GZZLUNOW",
    "940GZZLUNWH",
    "940GZZLUPNR",
    "940GZZLUPRD",
    "940GZZLURKW",
    "940GZZLURSM",
    "940GZZLURSP",
    "940GZZLURYL",
    "940GZZLUUXB",
    "940GZZLUWAF",
    "940GZZLUWHW",
    "940GZZLUWYP"
  ],
  "northern": [
    "940GZZLUACY",
    "940GZZLUAGL",
    "940GZZLUBLM",
    "940GZZLUBNK",
    "940GZZLUBOR",
    "940GZZLUBTK",
    "940GZZLUBTX",
    "940GZZLUBZP",
    "940GZZLUCFM",
    "940GZZLUCHX",
    "940GZZLUCND",
    "940GZZLUCPC",
    "940GZZLUCPN",
    "940GZZLUCPS",
    "940GZZLUCSD",
    "940GZZLUCTN",
    "940GZZLUEAC",
    "940GZZLUEFY",
    "940GZZLUEGW",
    "940GZZLUEMB",
    "940GZZLUEUS",
    "940GZZLUFYC",
    "940GZZLUGDG",
    "940GZZLUGGN",
    "940GZZLUHBT",
    "940GZZLUHCL",
    "940GZZLUHGT",
    "940GZZLUHTD",
    "940GZZLUKNG",
    "940GZZLUKSH",
    "940GZZLUKSX",
    "940GZZLULNB",
    "940GZZLULSQ",
    "940GZZLUMDN",
    "940GZZLUMGT",
    "940GZZLUMHL",
    "940GZZLUMTC",
    "940GZZLUODS",
    "940GZZLUOVL",
    "940GZZLUSKW",
    "940GZZLUSWN",
    "940GZZLUTAW",
    "940GZZLUTBC",
    "940GZZLUTBY",
    "940GZZLUTCR",
    "940GZZLUTFP",
    "940GZZLUWFN",
    "940GZZLUWLO",
    "940GZZLUWOP",
    "940GZZLUWRR"
  ],
  "piccadilly": [
    "910GENFCOAK",
    "940GZZLUACT",
    "940GZZLUALP",
    "940GZZLUASG",
    "940GZZLUASL",
    "940GZZLUBDS",
    "940GZZLUBOS",
    "940GZZLUBSC",
    "940GZZLUCAR",
    "940GZZLUCGN",
    "940GZZLUCKS",
    "940GZZLUCWP",
    "940GZZLUEAE",
    "940GZZLUECM",
    "940GZZLUECT",
    "940GZZLUFPK",
    "940GZZLUGPK",
    "940GZZLUGTR",
    "940GZZLUHBN",
    "940GZZLUHGD",
    "940GZZLUHNX",
    "940GZZLUHPC",
    "940GZZLUHR4",
    "940GZZLUHR5",
    "940GZZLUHRC",
    "940GZZLUHSD",
    "940GZZLUHWC",
    "940GZZLUHWE",
    "940GZZLUHWT",
    "940GZZLUHWY",
    "940GZZLUICK",
    "940GZZLUKNB",
    "940GZZLUKSX",
    "940GZZLULSQ",
    "940GZZLUMRH",
    "940GZZLUNEN",
    "940GZZLUNFD",
    "940GZZLUOAK",
    "940GZZLUOSY",
    "940GZZLUPCC",
    "940GZZLUPKR",
    "940GZZLURSM",
    "940GZZLURSP",
    "940GZZLURSQ",
    "940GZZLURVP",
    "940GZZLURYL",
    "940GZZLUSEA",
    "940GZZLUSFB",
    "940GZZLUSGT",
    "940GZZLUSHH",
    "940GZZLUSKS",
    "940GZZLUSUH",
    "940GZZLUSUT",
    "940GZZLUTNG",
    "940GZZLUTPN",
    "940GZZLUUXB",
    "940GZZLUWOG"
  ],
  "victoria": [
    "940GZZLUBLR",
    "940GZZLUBXN",
    "940GZZLUEUS",
    "940GZZLUFPK",
    "940GZZLUGPK",
    "940GZZLUHAI",
    "940GZZLUKSX",
    "940GZZLUOXC",
    "940GZZLUPCO",
    "940GZZLUSKW",
    "940GZZLUSVS",
    "940GZZLUTMH",
    "940GZZLUVIC",
    "940GZZLUVXL",
    "940GZZLUWRR",
    "940GZZLUWWL"
  ],
  "waterloo-city": [
    "940GZZLUBNK",
    "940GZZLUWLO"
  ]
};
